[general]
user_name = "gr00ss"
host_name = "wagner"
debug = false
cursor = "_"
show_cursor = true
blink_cursor = false
fps = 15

[colors]
background = "#33fa0bff"
foreground = "#c9d1d9"

